# Site
name: 'Tom Ordonez'
description: 'Analytics, Data Science, Recruiting'
logo: 
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'tomordonez-com'
email: 
mailchimp-list: 

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    tom:
      name: Tom
      site: https://www.tomordonez.com
      avatar: assets/images/tom.jpg
      bio: "Hi, I am Tom"
      twitter: https://twitter.com/tomordonez
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: tom
      avatar: assets/images/tom.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
